"""Initial Migration

Revision ID: 071e492c3a32
Revises: c493bb7b19c3
Create Date: 2022-05-06 16:05:03.389788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '071e492c3a32'
down_revision = 'c493bb7b19c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_path')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
