"""Initial Migration

Revision ID: 808f35cba8b6
Revises: 5b069cade387
Create Date: 2022-05-06 14:38:00.387693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '808f35cba8b6'
down_revision = '5b069cade387'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###
